# This pipeline is intentionally disabled
# It exists to prevent Azure DevOps from running the default pipeline.
# Real deployment is handled by GitHub Actions now.

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Azure pipeline disabled. Using GitHub Actions for CI/CD."
  displayName: "Disable notice"
