trigger:
  branches:
    include:
      - main

variables:
  imageName: 'aks-pipeline'
  acrLoginServer: 'azureprojects123.azurecr.io'
  kubernetesNamespace: 'default'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Build
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-sub-connection'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logging in to ACR..."
                az acr login --name <your-acr-name>
                
                echo "Building image..."
                docker build -t $acrLoginServer/$imageName:latest .
                
                echo "Pushing image..."
                docker push $acrLoginServer/$imageName:latest

  - stage: SecurityScan
    displayName: 'Run Terrascan'
    jobs:
      - job: Scan
        steps:
          - script: |
              docker run --rm -v $(System.DefaultWorkingDirectory):/iac aquasec/terrascan scan -d /iac
            displayName: "Run Terrascan Scan"

  - stage: Deploy
    displayName: 'Deploy to AKS'
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'azure-sub-connection'
              azureResourceGroup: '<your-resource-group>'
              kubernetesCluster: 'aks-pipeline-cluster'
              namespace: 'default'
              command: apply
              useConfigurationFile: true
              configuration: |
                manifests/deployment.yaml
                manifests/service.yaml
