apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-store-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-store-demo
  template:
    metadata:
      labels:
        app: aks-store-demo
    spec:
      containers:
      - name: aks-store-demo
        image: azureprojects123.azurecr.io/aks-store-demo:latest
        ports:
        - containerPort: 80
