apiVersion: v1
kind: Service
metadata:
  name: aks-store-demo-service
spec:
  selector:
    app: aks-store-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
