apiVersion: v1
kind: Service
metadata:
  name: aks-store-demo-service
spec:
  selector:
    app: aks-store-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # Public-facing port
      targetPort: 3000  # Internal container port
